apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: spring-petclinic
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32010
  selector:
    app: spring-petclinic
    tier: nginx