# Project information
site_name: Kubernetes Logging and Monitoring
site_url: https://ibm.github.io/kubernetes-logging-and-monitoring
site_author: IBM Developer

# Repository
repo_name: kubernetes-logging-and-monitoring
repo_url: https://github.com/ibm/kubernetes-logging-and-monitoring
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome: README.md
  - Setup: setup/README.md
  - Logging:
    - LogDNA:
      - Introduction: logdna/lab-0/README.md
      - Lab 1. LogDNA Install: logdna/lab-1/README.md
      - Lab 2. Deploy Application: logdna/lab-2/README.md
      - Lab 3. Analyze Logs: logdna/lab-3/README.md
      - Lab 4. Log Streaming: logdna/lab-4/README.md
  - Monitoring:
    - SysDig:
      - Lab 0. SysDig Install: lab-1/README.md
      - Lab 1. Hookup: lab-2/README.md

  - References:
    - Additional Resources: resources/RESOURCES.md
    - Contributors: resources/CONTRIBUTORS.md
    - MkDocs Cheatsheet: resources/MKDOCS.md
    - Admin Guide: resources/ADMIN.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2021 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: ibm_8bar_reverse_2
  features:
    #- navigation.tabs
    - navigation.instant
  palette:
    scheme: default
    primary: black
    accent: blue
  custom_dir: overrides

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde