kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-log-analysis-deployment
spec:
  selector:
    matchLabels:
      run: app-log-analysis
  replicas: 2
  template:
    metadata:
      labels:
        run: app-log-analysis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
    spec:
      containers:
        - name: app-log-analysis
          image: rojanjose/observe-test:v1.0
          ports:
            - containerPort: 8001

---
kind: Service
apiVersion: v1
metadata:
  name: app-log-analysis-svc
  labels:
    run: app-log-analysis
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8001
      nodePort: 32009
  selector:
    run: app-log-analysis
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: app-log-analysis-ingress
spec:
  rules:
  - host: observe.<INGRESS_SUBDOMAIN>
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: app-log-analysis-svc
          servicePort: 80
