apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-image
  labels:
    app: spring-petclinic
spec:
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: spring-petclinic
      tier: rating

  template:
    metadata:
      labels:
        app: spring-petclinic
        tier: rating
    spec:
      containers:
        - image: leezhang/missing-image:latest
          imagePullPolicy: Always
          name: missing-image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: missing-image-service
  labels:
    app: spring-petclinic
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32023
  selector:
    app: spring-petclinic
    tier: rating